-- ============================================================
-- Step 1: All DDL — dimensions, staging, fact table
-- Database: aml_db (MySQL 8.0+)
-- Run: mysql -u root -p aml_db < sql/01_schema.sql
-- ============================================================
