-- ============================================================
-- Step 2: Bulk load CSV into staging via LOAD DATA INFILE
-- Database: aml_db (MySQL 8.0+)
-- Run: mysql -u root -p aml_db < sql/02_load.sql
-- ============================================================
