-- ============================================================
-- Step 5: Data quality — duplicates, nulls, orphans
-- Database: aml_db (MySQL 8.0+)
-- Run: mysql -u root -p aml_db < sql/05_cleaning.sql
-- ============================================================
